# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# See : https://github.com/monday9pm/Hermes-Poster
name: Forword CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: Ana06/get-changed-files@v2.2.0
      id: abc
      with:
        format: space-delimited
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Printing
      run: |
        echo "All:"
        echo "${{ steps.abc.outputs.all }}"
        echo "Added:"
        echo "${{ steps.abc.outputs.added }}"
        echo "Removed:"
        echo "${{ steps.abc.outputs.removed }}"
        echo "Renamed:"
        echo "${{ steps.abc.outputs.renamed }}"
        echo "Modified:"
        echo "${{ steps.abc.outputs.modified }}"
        echo "Added+Modified:"
        echo "${{ steps.abc.outputs.added_modified }}"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    # from Github Repository Secrets
    - run: echo "Generate Configs..."
    - run: echo "${{ secrets.TEST_1 }}" >> action-secret.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm start
